### ISSUE TITLE
Readme > Steam Mini has a broken link to the Forum

### ISSUE THREAD

**Issue by bettafo** [darklinkpower/PlayniteScriptExtensions#27]
Like the tilte says: the readme of PlayniteScriptsExtensions Github has a broken link under the section: Steam Mini.
Cheers

**Comment by darklinkpower** [comment]
That extension is no longer being worked on since it was replaced by this other extension that has the same functionality https://playnite.link/forum/thread-659.html

The readme has not been updated for some time, I'll be updating all information when the work for the Playnite 9 extension releases is ready.
