### ISSUE TITLE
Auto launch GFN games

### ISSUE THREAD

**Issue by maxwell-01** [darklinkpower/PlayniteScriptExtensions#3]
Love that I can filter by Geforce Now Enabled games, thank you for that!

However I wondered whether it was possible to set launching from GFN the default option if the game is not installed. I also wondered if it was possible to show the game as installed if it was on GFN (I filter out uninstalled games from the view).

Keep up the good work!

**Comment by darklinkpower** [comment]
I'm reluctant to modify the default play action or installation status of other games since they both of those properties are (and should be) managed by their own library plugins. Modifying those things could lead to issues later when you want to install the games in their own client and they will also revert their installation status when you update the library of the game source.

I think the second one should do no harm. I'll add this as a new feature in a new version, just remember that the installation status will revert when updating the library.

**Comment by darklinkpower** [comment]
When this is implemented I will add an option to start games with the default Play action: https://github.com/JosefNemec/Playnite/issues/1852

I added the Installation Status function in v1.3

**Comment by darklinkpower** [comment]
Closing issue, it will be tracked in the plugin repository https://github.com/darklinkpower/PlaynitePlugin-NVIDIAGeForceNowEnabler/issues/1
